FROM nginx:1.13.2-alpine
MAINTAINER Rob McLarty <r@robmclarty.com> (https://robmclarty.com)

RUN mkdir -p /srv/opt/app
WORKDIR /srv/opt/app

RUN rm /etc/nginx/nginx.conf

COPY build/ /srv/opt/app/
COPY config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY config/nginx/app.conf /etc/nginx/sites-enabled/app.conf

EXPOSE 80 443

CMD ["nginx"]
